const districts_of_india = [
    "Nicobars, Andaman and Nicobar",
    "North and Middle Andaman, Andaman and Nicobar",
    "South Andaman, Andaman and Nicobar",
    "Adilabad, Telangana",
    "Bhadradri Kothagudem, Telangana",
    "Hyderabad, Telangana",
    "Jagtial, Telangana",
    "Jangaon, Telangana",
    "Jayashankar Bhupalpally, Telangana",
    "Jogulamba Gadwal, Telangana",
    "Kamareddy, Telangana",
    "Karimnagar, Telangana",
    "Khammam, Telangana",
    "Komaram Bheem, Telangana",
    "Mahabubabad, Telangana",
    "Mahbubnagar, Telangana",
    "Mancherial, Telangana",
    "Medak, Telangana",
    "Medchal–Malkajgiri, Telangana",
    "Nagarkurnool, Telangana",
    "Nalgonda, Telangana",
    "Nirmal, Telangana",
    "Nizamabad, Telangana",
    "Peddapalli, Telangana",
    "Rajanna Sircilla, Telangana",
    "Ranga Reddy, Telangana",
    "Sangareddy, Telangana",
    "Siddipet, Telangana",
    "Suryapet, Telangana",
    "Vikarabad, Telangana",
    "Wanaparthy, Telangana",
    "Warangal Rural, Telangana",
    "Warangal Urban, Telangana",
    "Yadadri Bhuvanagiri, Telangana",
    "Dima Hasao, Assam",
    "East Kameng, Arunachal Pradesh",
    "East Siang, Arunachal Pradesh",
    "Kamle, Arunachal Pradesh",
    "Kra Daadi, Arunachal Pradesh",
    "Kurung Kumey, Arunachal Pradesh",
    "Lepa Rada, Arunachal Pradesh",
    "Lohit, Arunachal Pradesh",
    "Longding, Arunachal Pradesh",
    "Lower Dibang Valley, Arunachal Pradesh",
    "Lower Siang, Arunachal Pradesh",
    "Lower Subansiri, Arunachal Pradesh",
    "Namsai, Arunachal Pradesh",
    "Pakke Kessang, Arunachal Pradesh",
    "Papum Pare, Arunachal Pradesh",
    "Shi Yomi, Arunachal Pradesh",
    "Siang, Arunachal Pradesh",
    "Tawang, Arunachal Pradesh",
    "Tirap, Arunachal Pradesh",
    "Upper Siang, Arunachal Pradesh",
    "Upper Subansiri, Arunachal Pradesh",
    "West Kameng, Arunachal Pradesh",
    "West Siang, Arunachal Pradesh",
    "Baksa, Assam",
    "Barpeta, Assam",
    "Biswanath, Assam",
    "Bongaigaon, Assam",
    "Cachar, Assam",
    "Charaideo, Assam",
    "Chirang, Assam",
    "Darrang, Assam",
    "Dhemaji, Assam",
    "Dhubri, Assam",
    "Dibrugarh, Assam",
    "Dima Hasao, Assam",
    "Goalpara, Assam",
    "Golaghat, Assam",
    "Hailakandi, Assam",
    "Hojai, Assam",
    "Jorhat, Assam",
    "Kamrup, Assam",
    "Kamrup Metropolitan, Assam",
    "Karbi Anglong, Assam",
    "Karimganj, Assam",
    "Kokrajhar, Assam",
    "Lakhimpur, Assam",
    "Majuli, Assam",
    "Morigaon, Assam",
    "Nagaon, Assam",
    "Nalbari, Assam",
    "Sivasagar, Assam",
    "Sonitpur, Assam",
    "South Salmara-Mankachar, Assam",
    "Tinsukia, Assam",
    "Udalguri, Assam",
    "West Karbi Anglong, Assam",
    "Araria, Bihar",
    "Arwal, Bihar",
    "Aurangabad, Bihar",
    "Banka, Bihar",
    "Begusarai, Bihar",
    "Bhagalpur, Bihar",
    "Bhojpur, Bihar",
    "Buxar, Bihar",
    "Darbhanga, Bihar",
    "East Champaran, Bihar",
    "Gaya, Bihar",
    "Gopalganj, Bihar",
    "Jamui, Bihar",
    "Jehanabad, Bihar",
    "Kaimur, Bihar",
    "Katihar, Bihar",
    "Khagaria, Bihar",
    "Kishanganj, Bihar",
    "Lakhisarai, Bihar",
    "Madhepura, Bihar",
    "Madhubani, Bihar",
    "Munger, Bihar",
    "Muzaffarpur, Bihar",
    "Nalanda, Bihar",
    "Nawada, Bihar",
    "Patna, Bihar",
    "Purnia, Bihar",
    "Rohtas, Bihar",
    "Saharsa, Bihar",
    "Samastipur, Bihar",
    "Saran, Bihar",
    "Sheikhpura, Bihar",
    "Sheohar, Bihar",
    "Sitamarhi, Bihar",
    "Siwan, Bihar",
    "Supaul, Bihar",
    "Vaishali, Bihar",
    "West Champaran, Bihar",
    "Chandigarh, Chandigarh",
    "Balod, Chhattisgarh",
    "Baloda Bazar, Chhattisgarh",
    "Balrampur, Chhattisgarh",
    "Bastar, Chhattisgarh",
    "Bemetara, Chhattisgarh",
    "Bijapur, Chhattisgarh",
    "Bilaspur, Chhattisgarh",
    "Dantewada, Chhattisgarh",
    "Dhamtari, Chhattisgarh",
    "Durg, Chhattisgarh",
    "Gariaband, Chhattisgarh",
    "Janjgir-Champa, Chhattisgarh",
    "Jashpur, Chhattisgarh",
    "Kabirdham, Chhattisgarh",
    "Kanker, Chhattisgarh",
    "Kondagaon, Chhattisgarh",
    "Korba, Chhattisgarh",
    "Koriya, Chhattisgarh",
    "Mahasamund, Chhattisgarh",
    "Mungeli, Chhattisgarh",
    "Narayanpur, Chhattisgarh",
    "Raigarh, Chhattisgarh",
    "Raipur, Chhattisgarh",
    "Rajnandgaon, Chhattisgarh",
    "Sukma, Chhattisgarh",
    "Surajpur, Chhattisgarh",
    "Surguja, Chhattisgarh",
    "Dadra and Nagar Haveli, Daman and Diu",
    "Central Delhi, Delhi",
    "East Delhi, Delhi",
    "New Delhi, Delhi",
    "North Delhi, Delhi",
    "North East Delhi, Delhi",
    "North West Delhi, Delhi",
    "Shahdara, Delhi",
    "South Delhi, Delhi",
    "South East Delhi, Delhi",
    "South West Delhi, Delhi",
    "West Delhi, Delhi",
    "North Goa, Goa",
    "South Goa, Goa",
    "Ahmedabad, Gujarat",
    "Amreli, Gujarat",
    "Anand, Gujarat",
    "Aravalli, Gujarat",
    "Banaskantha, Gujarat",
    "Bharuch, Gujarat",
    "Bhavnagar, Gujarat",
    "Botad, Gujarat",
    "Chhota Udaipur, Gujarat",
    "Dahod, Gujarat",
    "Dang, Gujarat",
    "Devbhoomi Dwarka, Gujarat",
    "Gandhinagar, Gujarat",
    "Gir Somnath, Gujarat",
    "Jamnagar, Gujarat",
    "Junagadh, Gujarat",
    "Kheda, Gujarat",
    "Kutch, Gujarat",
    "Mahisagar, Gujarat",
    "Mehsana, Gujarat",
    "Morbi, Gujarat",
    "Narmada, Gujarat",
    "Navsari, Gujarat",
    "Panchmahal, Gujarat",
    "Patan, Gujarat",
    "Porbandar, Gujarat",
    "Rajkot, Gujarat",
    "Sabarkantha, Gujarat",
    "Surat, Gujarat",
    "Surendranagar, Gujarat",
    "Tapi, Gujarat",
    "Vadodara, Gujarat",
    "Valsad, Gujarat",
    "Ambala, Haryana",
    "Bhiwani, Haryana",
    "Charkhi Dadri, Haryana",
    "Faridabad, Haryana",
    "Fatehabad, Haryana",
    "Gurugram, Haryana",
    "Hisar, Haryana",
    "Jhajjar, Haryana",
    "Jind, Haryana",
    "Kaithal, Haryana",
    "Karnal, Haryana",
    "Kurukshetra, Haryana",
    "Mahendragarh, Haryana",
    "Nuh, Haryana",
    "Palwal, Haryana",
    "Panchkula, Haryana",
    "Panipat, Haryana",
    "Rewari, Haryana",
    "Rohtak, Haryana",
    "Sirsa, Haryana",
    "Sonipat, Haryana",
    "Yamunanagar, Haryana",
    "Bilaspur, Himachal Pradesh",
    "Chamba, Himachal Pradesh",
    "Hamirpur, Himachal Pradesh",
    "Kangra, Himachal Pradesh",
    "Kinnaur, Himachal Pradesh",
    "Kullu, Himachal Pradesh",
    "Lahaul and Spiti, Himachal Pradesh",
    "Mandi, Himachal Pradesh",
    "Shimla, Himachal Pradesh",
    "Sirmaur, Himachal Pradesh",
    "Solan, Himachal Pradesh",
    "Una, Himachal Pradesh",
    "Anantnag, Jammu and Kashmir",
    "Bandipora, Jammu and Kashmir",
    "Baramulla, Jammu and Kashmir",
    "Budgam, Jammu and Kashmir",
    "Doda, Jammu and Kashmir",
    "Ganderbal, Jammu and Kashmir",
    "Jammu, Jammu and Kashmir",
    "Kathua, Jammu and Kashmir",
    "Kishtwar, Jammu and Kashmir",
    "Kulgam, Jammu and Kashmir",
    "Kupwara, Jammu and Kashmir",
    "Poonch, Jammu and Kashmir",
    "Pulwama, Jammu and Kashmir",
    "Rajouri, Jammu and Kashmir",
    "Ramban, Jammu and Kashmir",
    "Reasi, Jammu and Kashmir",
    "Samba, Jammu and Kashmir",
    "Shopian, Jammu and Kashmir",
    "Srinagar, Jammu and Kashmir",
    "Udhampur, Jammu and Kashmir",
    "Bokaro, Jharkhand",
    "Chatra, Jharkhand",
    "Deoghar, Jharkhand",
    "Dhanbad, Jharkhand",
    "Dumka, Jharkhand",
    "East Singhbhum, Jharkhand",
    "Garhwa, Jharkhand",
    "Giridih, Jharkhand",
    "Godda, Jharkhand",
    "Gumla, Jharkhand",
    "Hazaribagh, Jharkhand",
    "Jamtara, Jharkhand",
    "Khunti, Jharkhand",
    "Koderma, Jharkhand",
    "Latehar, Jharkhand",
    "Lohardaga, Jharkhand",
    "Pakur, Jharkhand",
    "Palamu, Jharkhand",
    "Ramgarh, Jharkhand",
    "Ranchi, Jharkhand",
    "Sahibganj, Jharkhand",
    "Seraikela Kharsawan, Jharkhand",
    "Simdega, Jharkhand",
    "West Singhbhum, Jharkhand",
    "Bagalkot, Karnataka",
    "Ballari, Karnataka",
    "Belagavi, Karnataka",
    "Bengaluru Rural, Karnataka",
    "Bengaluru Urban, Karnataka",
    "Bidar, Karnataka",
    "Chamarajanagar, Karnataka",
    "Chikkaballapur, Karnataka",
    "Chikkamagaluru, Karnataka",
    "Chitradurga, Karnataka",
    "Dakshina Kannada, Karnataka",
    "Davanagere, Karnataka",
    "Dharwad, Karnataka",
    "Gadag, Karnataka",
    "Hassan, Karnataka",
    "Haveri, Karnataka",
    "Kalaburagi, Karnataka",
    "Kodagu, Karnataka",
    "Kolar, Karnataka",
    "Koppal, Karnataka",
    "Mandya, Karnataka",
    "Mysuru, Karnataka",
    "Raichur, Karnataka",
    "Ramanagara, Karnataka",
    "Shivamogga, Karnataka",
    "Tumakuru, Karnataka",
    "Udupi, Karnataka",
    "Uttara Kannada, Karnataka",
    "Vijayapura, Karnataka",
    "Yadgir, Karnataka",
    "Alappuzha, Kerala",
    "Ernakulam, Kerala",
    "Idukki, Kerala",
    "Kannur, Kerala",
    "Kasaragod, Kerala",
    "Kollam, Kerala",
    "Kottayam, Kerala",
    "Kozhikode, Kerala",
    "Malappuram, Kerala",
    "Palakkad, Kerala",
    "Pathanamthitta, Kerala",
    "Thiruvananthapuram, Kerala",
    "Thrissur, Kerala",
    "Wayanad, Kerala",
    "Kargil, Ladakh",
    "Leh, Ladakh",
    "Ahmednagar, Maharashtra",
    "Akola, Maharashtra",
    "Amravati, Maharashtra",
    "Aurangabad, Maharashtra",
    "Beed, Maharashtra",
    "Bhandara, Maharashtra",
    "Buldhana, Maharashtra",
    "Chandrapur, Maharashtra",
    "Dhule, Maharashtra",
    "Gadchiroli, Maharashtra",
    "Gondia, Maharashtra",
    "Hingoli, Maharashtra",
    "Jalgaon, Maharashtra",
    "Jalna, Maharashtra",
    "Kolhapur, Maharashtra",
    "Latur, Maharashtra",
    "Mumbai City, Maharashtra",
    "Mumbai Suburban, Maharashtra",
    "Nagpur, Maharashtra",
    "Nanded, Maharashtra",
    "Nandurbar, Maharashtra",
    "Nashik, Maharashtra",
    "Osmanabad, Maharashtra",
    "Palghar, Maharashtra",
    "Parbhani, Maharashtra",
    "Pune, Maharashtra",
    "Raigad, Maharashtra",
    "Ratnagiri, Maharashtra",
    "Sangli, Maharashtra",
    "Satara, Maharashtra",
    "Sindhudurg, Maharashtra",
    "Solapur, Maharashtra",
    "Thane, Maharashtra",
    "Wardha, Maharashtra",
    "Washim, Maharashtra",
    "Yavatmal, Maharashtra",
    "Bishnupur, Manipur",
    "Chandel, Manipur",
    "Churachandpur, Manipur",
    "Imphal East, Manipur",
    "Imphal West, Manipur",
    "Jiribam, Manipur",
    "Kakching, Manipur",
    "Kamjong, Manipur",
    "Kangpokpi, Manipur",
    "Noney, Manipur",
    "Pherzawl, Manipur",
    "Senapati, Manipur",
    "Tamenglong, Manipur",
    "Tengnoupal, Manipur",
    "Thoubal, Manipur",
    "Ukhrul, Manipur",
    "East Garo Hills, Meghalaya",
    "East Jaintia Hills, Meghalaya",
    "East Khasi Hills, Meghalaya",
    "North Garo Hills, Meghalaya",
    "Ri Bhoi, Meghalaya",
    "South Garo Hills, Meghalaya",
    "South West Garo Hills, Meghalaya",
    "South West Khasi Hills, Meghalaya",
    "West Garo Hills, Meghalaya",
    "West Jaintia Hills, Meghalaya",
    "West Khasi Hills, Meghalaya",
    "Aizawl, Mizoram",
    "Champhai, Mizoram",
    "Hnahthial, Mizoram",
    "Khawzawl, Mizoram",
    "Kolasib, Mizoram",
    "Lawngtlai, Mizoram",
    "Lunglei, Mizoram",
    "Mamit, Mizoram",
    "Saiha, Mizoram",
    "Saitual, Mizoram",
    "Serchhip, Mizoram",
    "Dimapur, Nagaland",
    "Kiphire, Nagaland",
    "Kohima, Nagaland",
    "Longleng, Nagaland",
    "Mokokchung, Nagaland",
    "Mon, Nagaland",
    "Peren, Nagaland",
    "Phek, Nagaland",
    "Tuensang, Nagaland",
    "Wokha, Nagaland",
    "Zunheboto, Nagaland",
    "Angul, Odisha",
    "Balangir, Odisha",
    "Balasore, Odisha",
    "Bargarh, Odisha",
    "Bhadrak, Odisha",
    "Boudh, Odisha",
    "Cuttack, Odisha",
    "Debagarh, Odisha",
    "Dhenkanal, Odisha",
    "Gajapati, Odisha",
    "Ganjam, Odisha",
    "Jagatsinghpur, Odisha",
    "Jajpur, Odisha",
    "Jharsuguda, Odisha",
    "Kalahandi, Odisha",
    "Kandhamal, Odisha",
    "Kendrapara, Odisha",
    "Kendujhar, Odisha",
    "Khordha, Odisha",
    "Koraput, Odisha",
    "Malkangiri, Odisha",
    "Mayurbhanj, Odisha",
    "Nabarangpur, Odisha",
    "Nayagarh, Odisha",
    "Nuapada, Odisha",
    "Puri, Odisha",
    "Rayagada, Odisha",
    "Sambalpur, Odisha",
    "Subarnapur, Odisha",
    "Sundargarh, Odisha",
    "Karaikal, Puducherry",
    "Mahe, Puducherry",
    "Puducherry, Puducherry",
    "Yanam, Puducherry",
    "Amritsar, Punjab",
    "Barnala, Punjab",
    "Bathinda, Punjab",
    "Faridkot, Punjab",
    "Fatehgarh Sahib, Punjab",
    "Fazilka, Punjab",
    "Ferozepur, Punjab",
    "Gurdaspur, Punjab",
    "Hoshiarpur, Punjab",
    "Jalandhar, Punjab",
    "Kapurthala, Punjab",
    "Ludhiana, Punjab",
    "Mansa, Punjab",
    "Moga, Punjab",
    "Muktsar, Punjab",
    "Pathankot, Punjab",
    "Patiala, Punjab",
    "Rupnagar, Punjab",
    "Sahibzada Ajit Singh Nagar, Punjab",
    "Sangrur, Punjab",
    "Shahid Bhagat Singh Nagar, Punjab",
    "Sri Muktsar Sahib, Punjab",
    "Tarn Taran, Punjab",
    "Ajmer, Rajasthan",
    "Alwar, Rajasthan",
    "Banswara, Rajasthan",
    "Baran, Rajasthan",
    "Barmer, Rajasthan",
    "Bharatpur, Rajasthan",
    "Bhilwara, Rajasthan",
    "Bikaner, Rajasthan",
    "Bundi, Rajasthan",
    "Chittorgarh, Rajasthan",
    "Churu, Rajasthan",
    "Dausa, Rajasthan",
    "Dholpur, Rajasthan",
    "Dungarpur, Rajasthan",
    "Hanumangarh, Rajasthan",
    "Jaipur, Rajasthan",
    "Jaisalmer, Rajasthan",
    "Jalore, Rajasthan",
    "Jhalawar, Rajasthan",
    "Jhunjhunu, Rajasthan",
    "Jodhpur, Rajasthan",
    "Karauli, Rajasthan",
    "Kota, Rajasthan",
    "Nagaur, Rajasthan",
    "Pali, Rajasthan",
    "Pratapgarh, Rajasthan",
    "Rajsamand, Rajasthan",
    "Sawai Madhopur, Rajasthan",
    "Sikar, Rajasthan",
    "Sirohi, Rajasthan",
    "Sri Ganganagar, Rajasthan",
    "Tonk, Rajasthan",
    "Udaipur, Rajasthan",
    "East Sikkim, Sikkim",
    "North Sikkim, Sikkim",
    "South Sikkim, Sikkim",
    "West Sikkim, Sikkim",
    "Ariyalur, Tamil Nadu",
    "Chengalpattu, Tamil Nadu",
    "Chennai, Tamil Nadu",
    "Coimbatore, Tamil Nadu",
    "Cuddalore, Tamil Nadu",
    "Dharmapuri, Tamil Nadu",
    "Dindigul, Tamil Nadu",
    "Erode, Tamil Nadu",
    "Kallakurichi, Tamil Nadu",
    "Kancheepuram, Tamil Nadu",
    "Kanyakumari, Tamil Nadu",
    "Karur, Tamil Nadu",
    "Krishnagiri, Tamil Nadu",
    "Madurai, Tamil Nadu",
    "Mayiladuthurai, Tamil Nadu",
    "Nagapattinam, Tamil Nadu",
    "Namakkal, Tamil Nadu",
    "Nilgiris, Tamil Nadu",
    "Perambalur, Tamil Nadu",
    "Pudukkottai, Tamil Nadu",
    "Ramanathapuram, Tamil Nadu",
    "Ranipet, Tamil Nadu",
    "Salem, Tamil Nadu",
    "Sivaganga, Tamil Nadu",
    "Tenkasi, Tamil Nadu",
    "Thanjavur, Tamil Nadu",
    "Theni, Tamil Nadu",
    "Thoothukudi, Tamil Nadu",
    "Tiruchirappalli, Tamil Nadu",
    "Tirunelveli, Tamil Nadu",
    "Tirupathur, Tamil Nadu",
    "Tiruppur, Tamil Nadu",
    "Tiruvallur, Tamil Nadu",
    "Tiruvannamalai, Tamil Nadu",
    "Tiruvarur, Tamil Nadu",
    "Vellore, Tamil Nadu",
    "Viluppuram, Tamil Nadu",
    "Virudhunagar, Tamil Nadu",
    "Adilabad, Telangana",
    "Bhadradri Kothagudem, Telangana",
    "Hyderabad, Telangana",
    "Jagtial, Telangana",
    "Jangaon, Telangana",
    "Jayashankar Bhupalpally, Telangana",
    "Jogulamba Gadwal, Telangana",
    "Kamareddy, Telangana",
    "Karimnagar, Telangana",
    "Khammam, Telangana",
    "Komaram Bheem, Telangana",
    "Mahabubabad, Telangana",
    "Mahbubnagar, Telangana",
    "Mancherial, Telangana",
    "Medak, Telangana",
    "Medchal–Malkajgiri, Telangana",
    "Nagarkurnool, Telangana",
    "Nalgonda, Telangana",
    "Nirmal, Telangana",
    "Nizamabad, Telangana",
    "Peddapalli, Telangana",
    "Rajanna Sircilla, Telangana",
    "Ranga Reddy, Telangana",
    "Sangareddy, Telangana",
    "Siddipet, Telangana",
    "Suryapet, Telangana",
    "Vikarabad, Telangana",
    "Wanaparthy, Telangana",
    "Warangal Rural, Telangana",
    "Warangal Urban, Telangana",
    "Yadadri Bhuvanagiri, Telangana",
    "Dhalai, Tripura",
    "Gomati, Tripura",
    "Khowai, Tripura",
    "North Tripura, Tripura",
    "Sepahijala, Tripura",
    "South Tripura, Tripura",
    "Unakoti, Tripura",
    "West Tripura, Tripura",
    "Agra, Uttar Pradesh",
    "Aligarh, Uttar Pradesh",
    "Ambedkar Nagar, Uttar Pradesh",
    "Amethi, Uttar Pradesh",
    "Amroha, Uttar Pradesh",
    "Auraiya, Uttar Pradesh",
    "Ayodhya, Uttar Pradesh",
    "Azamgarh, Uttar Pradesh",
    "Baghpat, Uttar Pradesh",
    "Bahraich, Uttar Pradesh",
    "Ballia, Uttar Pradesh",
    "Balrampur, Uttar Pradesh",
    "Banda, Uttar Pradesh",
    "Barabanki, Uttar Pradesh",
    "Bareilly, Uttar Pradesh",
    "Basti, Uttar Pradesh",
    "Bhadohi, Uttar Pradesh",
    "Bijnor, Uttar Pradesh",
    "Budaun, Uttar Pradesh",
    "Bulandshahr, Uttar Pradesh",
    "Chandauli, Uttar Pradesh",
    "Chitrakoot, Uttar Pradesh",
    "Deoria, Uttar Pradesh",
    "Etah, Uttar Pradesh",
    "Etawah, Uttar Pradesh",
    "Farrukhabad, Uttar Pradesh",
    "Fatehpur, Uttar Pradesh",
    "Firozabad, Uttar Pradesh",
    "Gautam Buddha Nagar, Uttar Pradesh",
    "Ghaziabad, Uttar Pradesh",
    "Ghazipur, Uttar Pradesh",
    "Gonda, Uttar Pradesh",
    "Gorakhpur, Uttar Pradesh",
    "Hamirpur, Uttar Pradesh",
    "Hapur, Uttar Pradesh",
    "Hardoi, Uttar Pradesh",
    "Hathras, Uttar Pradesh",
    "Jalaun, Uttar Pradesh",
    "Jaunpur, Uttar Pradesh",
    "Jhansi, Uttar Pradesh",
    "Kannauj, Uttar Pradesh",
    "Kanpur Dehat, Uttar Pradesh",
    "Kanpur Nagar, Uttar Pradesh",
    "Kasganj, Uttar Pradesh",
    "Kaushambi, Uttar Pradesh",
    "Kheri, Uttar Pradesh",
    "Kushinagar, Uttar Pradesh",
    "Lakhimpur Kheri, Uttar Pradesh",
    "Lalitpur, Uttar Pradesh",
    "Lucknow, Uttar Pradesh",
    "Maharajganj, Uttar Pradesh",
    "Mahoba, Uttar Pradesh",
    "Mainpuri, Uttar Pradesh",
    "Mathura, Uttar Pradesh",
    "Mau, Uttar Pradesh",
    "Meerut, Uttar Pradesh",
    "Mirzapur, Uttar Pradesh",
    "Moradabad, Uttar Pradesh",
    "Muzaffarnagar, Uttar Pradesh",
    "Pilibhit, Uttar Pradesh",
    "Pratapgarh, Uttar Pradesh",
    "Prayagraj, Uttar Pradesh",
    "Raebareli, Uttar Pradesh",
    "Rampur, Uttar Pradesh",
    "Saharanpur, Uttar Pradesh",
    "Sambhal, Uttar Pradesh",
    "Sant Kabir Nagar, Uttar Pradesh",
    "Shahjahanpur, Uttar Pradesh",
    "Shamli, Uttar Pradesh",
    "Shrawasti, Uttar Pradesh",
    "Siddharthnagar, Uttar Pradesh",
    "Sitapur, Uttar Pradesh",
    "Sonbhadra, Uttar Pradesh",
    "Sultanpur, Uttar Pradesh",
    "Unnao, Uttar Pradesh",
    "Varanasi, Uttar Pradesh",
    "Almora, Uttarakhand",
    "Bageshwar, Uttarakhand",
    "Chamoli, Uttarakhand",
    "Champawat, Uttarakhand",
    "Dehradun, Uttarakhand",
    "Haridwar, Uttarakhand",
    "Nainital, Uttarakhand",
    "Pauri Garhwal, Uttarakhand",
    "Pithoragarh, Uttarakhand",
    "Rudraprayag, Uttarakhand",
    "Tehri Garhwal, Uttarakhand",
    "Udham Singh Nagar, Uttarakhand",
    "Uttarkashi, Uttarakhand",
    "Alipurduar, West Bengal",
    "Bankura, West Bengal",
    "Birbhum, West Bengal",
    "Cooch Behar, West Bengal",
    "Dakshin Dinajpur, West Bengal",
    "Darjeeling, West Bengal",
    "Hooghly, West Bengal",
    "Howrah, West Bengal",
    "Jalpaiguri, West Bengal",
    "Jhargram, West Bengal",
    "Kalimpong, West Bengal",
    "Kolkata, West Bengal",
    "Malda, West Bengal",
    "Murshidabad, West Bengal",
    "Nadia, West Bengal",
    "North 24 Parganas, West Bengal",
    "Paschim Bardhaman, West Bengal",
    "Paschim Medinipur, West Bengal",
    "Purba Bardhaman, West Bengal",
    "Purba Medinipur, West Bengal",
    "Purulia, West Bengal",
    "South 24 Parganas, West Bengal",
    "Uttar Dinajpur, West Bengal"
]
export default districts_of_india;
